# Generated by Django 4.1.3 on 2022-12-06 08:47

from django.db import migrations
from accounts.models import CustomUser
from rest_framework.authtoken.models import Token


def create_bio_app_user(apps, schema_editor):
    CustomUser.objects.create_user(username="bio_app", password="bio_app")
    for user in CustomUser.objects.all():
        Token.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("authtoken", "0003_tokenproxy"),
    ]

    operations = [
        migrations.RunPython(
            create_bio_app_user, reverse_code=migrations.RunPython.noop
        ),
    ]
