services:
  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DBNAME:-booking_app}

  booking_api:
    build:
      context: ./django/
      target: base
    volumes:
      - ./django:/usr/src/app
    environment:
      DJANGO_DELAY: ${DJANGO_DELAY:-3}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME:-booking_app}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin}
      DJANGO_PRODUCTION_MODE: ${DJANGO_PRODUCTION_MODE:-false}

  bio_app:
    build:
      context: ./bio-app/
      target: base
    volumes:
      - ./bio-app:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    environment:
      VITE_BOOKING_API_HOST: ${BOOKING_API_HOST:-localhost}
      VITE_BOOKING_API_PORT: ${BOOKING_API_PORT:-8000}
      VITE_BOOKING_API_USERNAME: ${BOOKING_API_USERNAME:-bio_app}
      VITE_BOOKING_API_PASSWORD: ${BOOKING_API_PASSWORD:-bio_app}
    ports:
      - 3000:3000

volumes:
  # https://www.baeldung.com/ops/docker-exclude-sub-folder-when-adding-volume
  exclude:
    driver: local
