# Generated by Django 4.1.3 on 2022-11-11 10:51

from django.db import migrations
from django.utils import timezone


def make_dummy_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    BookableLocation = apps.get_model("bookingapi", "BookableLocation")
    Seat = apps.get_model("bookingapi", "Seat")
    LocationBooking = apps.get_model("bookingapi", "LocationBooking")
    SeatBooking = apps.get_model("bookingapi", "SeatBooking")
    
    user = User.objects.create_user(username="DummyUser", password="DummyPassword")
    bookable_location = BookableLocation.objects.create(
        name="DummyLocation", description="DummyDescription", created_by=user
    )
    seat = Seat.objects.create(
        name="DummySeat",
        bookable_location=bookable_location,
        created_by=user,
        description="DummyDescription",
        restricted=False,
    )
    location_booking = LocationBooking.objects.create(
        bookable_location=bookable_location,
        created_by=user,
        start_time=timezone.now() + timezone.timedelta(weeks=52),
        end_time=timezone.now() + timezone.timedelta(weeks=52, days=1),
        event_name="DummyEventName",
        event_description="DummyEventDescription",
    )
    SeatBooking.objects.create(
        customer="DummyCustomer",
        seat=seat,
        location_booking=location_booking,
        created_by=user,
    )

class Migration(migrations.Migration):

    dependencies = [
        ("bookingapi", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_dummy_data),
    ]
