# Generated by Django 4.1.3 on 2022-12-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    # Def a default constraint
    def add_default_constraint(apps, schema_editor):
        Constraints = apps.get_model("bookingapi", "Constraints")
        Constraints.objects.create(name="default")

    dependencies = [
        ("bookingapi", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            add_default_constraint, reverse_code=migrations.RunPython.noop
        ),
    ]
