# Generated by Django 4.1.3 on 2022-11-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingapi", "0002_test_dummy_data"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="seatbooking",
            constraint=models.UniqueConstraint(
                fields=("seat", "location_booking"),
                name="unique_seat_booking",
                violation_error_message="Seat already booked for this event",
            ),
        ),
    ]
